console.log('HOLA MUNDO');
console.log('ESTOY EDITANDO MI PRIMERA LINEA DE CODIGO EN JAVASCRIPT');
console.log('ESTOY APRENDIENDO A USAR GIT Y GITHUB');
console.log('ESTOY HACIENDO CAMBIOS EN MI PORTAFOLIO');